import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ADMIN_EMAIL, SAMPLE_DOCX, STATE_FILE, backendEnv } from "./env";

/** Runs after the web servers are up (Playwright starts them first): the database is migrated,
 * so the CLI can create the first administrator. */
export default function globalSetup(): void {
  const output = execFileSync(
    "uv",
    [
      "run",
      "--directory",
      path.join(__dirname, "..", "..", "backend"),
      "qc-agent",
      "create-admin",
      "--email",
      ADMIN_EMAIL,
      "--name",
      "E2E Admin",
    ],
    { encoding: "utf8", env: { ...process.env, ...backendEnv } },
  );
  const match = /Temporary password \(shown once\): (\S+)/.exec(output);
  if (!match) throw new Error(`create-admin did not print a temporary password:\n${output}`);
  mkdirSync(path.dirname(STATE_FILE), { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify({ email: ADMIN_EMAIL, password: match[1] }));

  // A small synthetic .docx for the upload flow, generated by python-docx from the backend's
  // environment so nothing binary is committed and no customer content is used.
  execFileSync(
    "uv",
    [
      "run",
      "--directory",
      path.join(__dirname, "..", "..", "backend"),
      "python",
      "-c",
      [
        "import sys",
        "from docx import Document",
        "d = Document()",
        "d.add_heading('Scope', level=1)",
        "d.add_paragraph('The system shall allow users to log in with a password and a one-time code.')",
        "d.add_paragraph('The system shall keep an audit log of every upload.')",
        "d.save(sys.argv[1])",
      ].join("\n"),
      SAMPLE_DOCX,
    ],
    { encoding: "utf8", env: { ...process.env, ...backendEnv } },
  );
}
